###
## flutter_basics\analysis_options.yaml
## Created Date: Monday, November 8th 2021, 9:09:43 am
## Author: Jedi Hero
## 
## Copyright (c) 2021 Jedi Hero
##

## Info





include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
